### PR TITLE
Implement a Light/Dark Mode Toggle 

### PR DESCRIPTION
**Pull request by Bishwajitpvt**
Implemented dark and light mode with toggle button  #44

### CODE REVIEW

**Comment by sivaguttikonda** [comment]
please share a screenshot @Bishwajitpvt

**Comment by Bishwajitpvt** [comment]
I have shared the screenshot in the  issue #44

**Comment by Bishwajitpvt** [comment]
if you want i can reshare it again

**Review by gschandrasekhar — COMMENTED** [review]
cool

**Pull request merged**
